name: Tests

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docs/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go build ./...
      - run: go vet ./...

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go test -v ./...

  acceptance-test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform-version:
          - "1.9.*"
          - "1.10.*"
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ matrix.terraform-version }}
          terraform_wrapper: false
      - uses: jdx/mise-action@v4
      - env:
          TF_ACC: "1"
        run: go test -v -cover ./...
        timeout-minutes: 10
